feat: [Connectivity] Add Swift Package Manager support for Connectivity spm
fluttercommunity/plus_plugins pull request #3173
Opened 2024-08-12 09:40 UTC by charafau

ref: https://github.com/fluttercommunity/plus_plugins/issues/3152

Another spm support

removed obsolete objc code, moved plugin to swift only, which avoid mixing swift project

2024-08-12 10:13 UTC, miquelbeltran requested changes
The example pubspec should not be changed.

Instead, use `melos bootstrap` as explained in the contributors document to setup the example project.

2024-08-12 10:13 UTC, miquelbeltran commented on packages/connectivity_plus/connectivity_plus/darwin/Classes/ConnectivityPlusPlugin.m
Would removing this code cause an issue on older apps still using Obj-C?

2024-08-12 10:13 UTC, miquelbeltran commented on packages/connectivity_plus/connectivity_plus/example/pubspec.yaml
Changes in this file should be reverted

2024-08-12 14:46 UTC, charafau commented on packages/connectivity_plus/connectivity_plus/darwin/Classes/ConnectivityPlusPlugin.m
I'm sure on 99% it won't. Example project works without changing anything, support for swift in plugin was here already.

2024-08-12 14:47 UTC, charafau commented
> The example pubspec should not be changed.
> 
> Instead, use `melos bootstrap` as explained in the contributors document to setup the example project.


Thank you Miguel, will educate myself with melon :)

2024-10-17 10:38 UTC, vbuberen approved these changes
Tested and everything works good. 

Thanks for another contribution!

2024-10-17 10:38 UTC, merged