feat(share_plus): Added excludedActivityTypes support for the iOS platform.
fluttercommunity/plus_plugins pull request #3376
Opened 2024-12-03 06:30 UTC by StanleyCocos

The iOS platform is missing the exclusion feature. This PR adds the platform exclusion functionality for iOS.

## Checklist

- [x] I read the [Contributor Guide](https://github.com/fluttercommunity/plus_plugins/blob/main/CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
- [x] I titled the PR using [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0).
- [x] I did not modify the `CHANGELOG.md` nor the plugin version in `pubspec.yaml` files.
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate that with a `!` in the title as explained in [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0)).
- [x] No, this is *not* a breaking change.

2024-12-03 07:07 UTC, miquelbeltran commented
Thanks for this contribution as well! We have to keep this one on hold because I plan to refactor the `share()` method parameters, as also discussed in https://github.com/fluttercommunity/plus_plugins/pull/3372

Your input on this topic would be appreciated as well.

2024-12-03 07:17 UTC, StanleyCocos commented
@miquelbeltran 
Thank you for your reply. 
I understand your plan now. If needed, I can still improve this PR after your plan.

2024-12-18 13:46 UTC, miquelbeltran commented
FYI, started working on the shareplus refactor, that should simplify adding this and other optional parameters: https://github.com/fluttercommunity/plus_plugins/pull/3404

2024-12-19 01:31 UTC, StanleyCocos commented
Hi, that's great! I've been studying the code in your branch. It's really well-organized and tidy. Next, I need to add the parameter excludedActivityType for this pull request (PR) to ShareParams. After that, I'll wait for you to finish merging xx into the main branch. Once that's done, I'll synchronize my changes accordingly.

2025-04-21 14:36 UTC, miquelbeltran commented
Thanks! I haven't looked too deep into it yet, but can you describe how it works in this PR, so I can understand the change better. 

And as well, add a bit of documentation about this feature on the `README.md` so users are aware of it.

2025-04-22 03:45 UTC, StanleyCocos commented
Let me briefly describe the changes in this PR:

- In share_plus_platform_interface, I declared a CupertinoActivityType enum and added it as a parameter to ShareParams. Before passing it to the iOS layer, it is transmitted as a string to make it easier for users to exclude unwanted share options on iOS and macOS.

-  On the iOS native side, the string passed from the Flutter layer is received and converted back into an enum, which is then applied to the share configuration.

-  In the example, I added a multi-selection page for easier testing. Due to structural issues, I also introduced a new MyApp class that returns a MaterialApp (this caused a number of structural and formatting changes).

2025-05-01 12:39 UTC, miquelbeltran reviewed
Just some comments, I like the overall idea. I will also have to test this somehow.

2025-05-01 12:39 UTC, miquelbeltran commented on packages/share_plus/share_plus_platform_interface/test/share_plus_platform_interface_test.dart
> +            excludedActivityType: null),
Trailing comma missing after `null`

2025-05-01 12:39 UTC, miquelbeltran commented on packages/share_plus/share_plus/README.md
> +For the list of supported excludedActivityTypes, you can refer to Apple’s [documentation](https://developer.apple.com/documentation/uikit/uiactivityviewcontroller/excludedactivitytypes/).
```suggestion
you can set the `excludedActivityTypes` array.
For the list of supported `excludedActivityTypes`, you can refer to Apple's [documentation](https://developer.apple.com/documentation/uikit/uiactivityviewcontroller/excludedactivitytypes/).
```

Small formatting suggestion

2025-05-01 12:39 UTC, miquelbeltran commented on packages/share_plus/share_plus/README.md
> +For the list of supported excludedActivityTypes, you can refer to Apple’s [documentation](https://developer.apple.com/documentation/uikit/uiactivityviewcontroller/excludedactivitytypes/).
Shouldn't devs check the `CupertinoActivityType` enum instead of the Apple docs?

2025-05-01 12:39 UTC, miquelbeltran commented on packages/share_plus/share_plus_platform_interface/lib/platform_interface/share_plus_platform.dart
> +  final List<CupertinoActivityType>? excludedActivityType;
Since it's an apple exclusive param, can we name it so it references that? e.g. `excludedCupertinoActivities` since the type is `CupertinoActivityType`.

2025-05-01 12:39 UTC, miquelbeltran commented on packages/share_plus/share_plus_platform_interface/test/share_plus_platform_interface_test.dart
> +          excludedActivityType: [CupertinoActivityType.airDrop]),
Missing trailing comma

2025-05-06 02:01 UTC, StanleyCocos commented on packages/share_plus/share_plus_platform_interface/lib/platform_interface/share_plus_platform.dart
> +  final List<CupertinoActivityType>? excludedActivityType;
Your suggestion is excellent — the naming alone makes the purpose clear to developers.

2025-05-06 02:03 UTC, StanleyCocos commented on packages/share_plus/share_plus_platform_interface/test/share_plus_platform_interface_test.dart
> +            excludedActivityType: null),
Thank you, it’s been updated.

2025-05-06 02:03 UTC, StanleyCocos commented on packages/share_plus/share_plus_platform_interface/test/share_plus_platform_interface_test.dart
> +          excludedActivityType: [CupertinoActivityType.airDrop]),
Thank you, it’s been updated.

2025-05-06 02:04 UTC, StanleyCocos commented on packages/share_plus/share_plus/README.md
> +For the list of supported excludedActivityTypes, you can refer to Apple’s [documentation](https://developer.apple.com/documentation/uikit/uiactivityviewcontroller/excludedactivitytypes/).
You’re right, it should be based on CupertinoActivityType first.

2025-06-17 09:12 UTC, StanleyCocos commented
@miquelbeltran 
Sorry to bother you. I noticed this request has been pending for quite a while. Do you have any plans to complete the code review soon?

2025-06-17 09:46 UTC, miquelbeltran commented on packages/share_plus/share_plus_platform_interface/lib/platform_interface/share_plus_platform.dart
> +}
What is this extension used for? I don't see it used in the PR

2025-06-17 09:47 UTC, miquelbeltran commented on packages/share_plus/share_plus_platform_interface/lib/platform_interface/share_plus_platform.dart
> +/// https://developer.apple.com/documentation/uikit/uiactivity/activitytype
This comment doesn't seem correct to me, as these are enum values not abstract classes. Can this be reworded differently?

2025-06-17 09:52 UTC, miquelbeltran commented on packages/share_plus/share_plus/ios/share_plus/Sources/share_plus/FPPSharePlusPlugin.m
> +  }
The variable names are a bit confusing here. `excludedActivityType` is the input parameter, which is an array (so it shouldn't be singular but plural), and I guess it contains the activity types as strings?

 Then `excludedActivityTypes` is the actual array with activity type "types".

I'd suggest refactoring this a bit. Maybe extract the conversion of array of Strings to array of Activity Types into a function.

And then move it up on the logic, e.g. right after `NSArray *excludedActivityType = arguments[@"excludedActivityType"];` in line 310. So all further calls to the share methods, e.g. `self shareUri` already pass an array of activity types and not an array of Strings.

2025-06-18 02:12 UTC, StanleyCocos commented on packages/share_plus/share_plus_platform_interface/lib/platform_interface/share_plus_platform.dart
> +}
It’s used at line 73 in method_channel_share. But I think turning it into a separate method might be a better approach now.

2025-06-18 02:13 UTC, StanleyCocos commented on packages/share_plus/share_plus_platform_interface/lib/platform_interface/share_plus_platform.dart
> +/// https://developer.apple.com/documentation/uikit/uiactivity/activitytype
You’re right — I may have overlooked updating the documentation here. It’s now been revised; could you please take another look?

2025-06-18 02:14 UTC, StanleyCocos commented on packages/share_plus/share_plus/ios/share_plus/Sources/share_plus/FPPSharePlusPlugin.m
> +  }
Thank you for your suggestion — I’ve made the adjustments. Much appreciated!

2025-06-23 13:35 UTC, miquelbeltran requested changes
Requesting one more change, and I think this would be completed. Thanks for keeping up with the PR!

2025-06-23 13:35 UTC, miquelbeltran commented on packages/share_plus/share_plus_platform_interface/lib/method_channel/method_channel_share.dart
> +
Sorry, I'll have to request another change. We renamed the variable `excludedCupertinoActivities` as it previously was `excludedActivityType`. However, I think it would be good if the map key would also be the same, to avoid confusion with that. I missed that when I first reviewed.

2025-06-23 13:48 UTC, miquelbeltran commented
Tested on iOS 18.5 simulator using the example app ✅

2025-06-24 01:29 UTC, StanleyCocos commented on packages/share_plus/share_plus_platform_interface/lib/method_channel/method_channel_share.dart
> +
Thank you for your suggestion. 

Slightly adjusted, but I still have some other thoughts.

I have a slightly different idea about this part. I think using excludedCupertinoActivities as the key name in the map may not be entirely appropriate, because accessing a key with “Cupertino” in its name on the iOS side feels a bit odd.

Also, I think if Android were to support a similar feature, we should still use this same key name to pass it down (even though Android doesn’t support it directly, it can potentially be handled by excluding package names).
If we do implement it for Android, I think we could introduce a new List<String> parameter for excluded package names.

2025-06-24 06:23 UTC, miquelbeltran commented on packages/share_plus/share_plus_platform_interface/lib/method_channel/method_channel_share.dart
> +
Hi! I don't see why would it feel weird to access a map value with the key `Cupertino` in it, as it is just the parsing of the parameters map, once read the value the variables don't need to be explicitly `Cupertino`.

> I think if Android were to support a similar feature, we should still use this same key name to pass it down 

I would disagree with that, I think keeping the params keys separated and explicit per platform (e.g. the Android one would be `excludedAndroidPackages`) will avoid confusion for devs not familiar with the codebase.

From the public API perspective, we should allow users to call to `share()` with both the Cupertino and the Android params in it, and internally it's simpler if we don't have a switch-case per platform but rather just copy each param into the corresponding params map.

2025-06-24 07:10 UTC, StanleyCocos commented on packages/share_plus/share_plus_platform_interface/lib/method_channel/method_channel_share.dart
> +
Alright, it’s just a minor naming style issue. I’ve already made the adjustment. 
Thank you

2025-06-24 08:48 UTC, miquelbeltran commented
Thanks for the changes, I think it's good to go now!

2025-06-24 08:50 UTC, miquelbeltran approved these changes

2025-06-24 08:52 UTC, merged