[connectivity_plus_windows] add ethernet support
fluttercommunity/plus_plugins pull request #463
Opened 2021-09-19 22:10 UTC by alexbatalov

## Description

Add ethernet as connectivity result - #399 for Windows.

One maybe not so obvious change is that `NetworkListener` now implements `INetworkEvents`. It allows to watch for connectivity changes on individual networks and then compute system-wide connectivity type. If you're connected to both Ethernet and Wi-Fi and then disconnecting Wi-Fi, `INetworkListManagerEvents` won't fire callback because overall system connectivity did not change.

For backward compatibility any Internet-connected interface that's not Ethernet is considered Wi-Fi.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/fluttercommunity/plus_plugins/blob/main/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

2021-09-30 18:31 UTC, mhadaily commented
can you merge with `main` and push one more time.

2021-10-02 10:59 UTC, mhadaily requested changes

2021-10-02 10:59 UTC, mhadaily commented on packages/connectivity_plus/connectivity_plus_windows/CHANGELOG.md
> +
Can you please add the same changelog (mention windows package) to the main package and pump the version accordingly  + you need to pump both windows package and main package 

https://github.com/alexbatalov/plus_plugins/blob/connectivity-plus-windows-ethernet/packages/connectivity_plus/connectivity_plus/pubspec.yaml

2021-10-02 11:40 UTC, alexbatalov commented
please check if get it right: incremented minor version on main package, incremented it's dependency on connectivity_plus_windows, mentioned windows support in main package changelog

2021-10-03 17:45 UTC, mhadaily approved these changes

2021-10-03 18:33 UTC, merged