ci: upgrade flutter from 2.2.1 to 2.5.2
fluttercommunity/plus_plugins pull request #476
Opened 2021-10-01 07:20 UTC by juliansteenbakker

## Description

This will upgrade the CI flutter version to 2.5.2.

## Related Issues

This will depend on #466 since it will not pass with the deprecated integration_test.
This is also blocking #442.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [ X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ X] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ X] All existing and new tests are passing.
- [X ] I updated/added relevant documentation (doc comments with `///`).
- [X ] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [ X] I read and followed the [Flutter Style Guide].
- [ X] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [X] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/fluttercommunity/plus_plugins/blob/main/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

2021-10-01 08:51 UTC, juliansteenbakker commented
This is blocked by #466

2021-10-01 19:42 UTC, juliansteenbakker commented
It seems like some tests are failing with latest flutter release. I'll check them and update this PR ASAP.

2021-10-01 19:44 UTC, mhadaily commented
thanks, I'll review again tomorrow morning.

2021-10-02 11:10 UTC, mhadaily requested changes
please consider my comments

2021-10-02 11:10 UTC, mhadaily commented on packages/package_info_plus/package_info_plus_windows/lib/src/file_version_info.dart
>  }
This PR is mentioning CI but we have a change in the package. can you take this out and send another PR for this. Please mention what this change is going to resolve.

2021-10-02 11:10 UTC, mhadaily commented on packages/package_info_plus/package_info_plus_windows/pubspec.yaml
> +version: 1.0.4
see above

2021-10-02 11:10 UTC, mhadaily commented on packages/package_info_plus/package_info_plus_windows/CHANGELOG.md
> +
see my comment

2021-10-02 17:30 UTC, juliansteenbakker commented on packages/package_info_plus/package_info_plus_windows/CHANGELOG.md
> +
Fixed, please see #491

2021-10-02 17:30 UTC, juliansteenbakker commented
I have moved the required changes to the windows package into #491

2021-10-03 17:43 UTC, mhadaily commented
thanks, I have prepared a new PR #489 that covers this. I'll close this PR but will consider your contribution for sure. you have done a great job. thanks

2021-10-03 17:43 UTC, closed without merging