Update the description of getAndroidId method
fluttercommunity/plus_plugins pull request #807
Opened 2022-03-27 02:28 UTC by martinoyovo

## Description

*Added the correct description about getAndroidId method*

## Related Issues

*https://github.com/fluttercommunity/plus_plugins/issues/769*

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated the version in `pubspec.yaml` and `CHANGELOG.md`.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/fluttercommunity/plus_plugins/blob/main/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

2022-04-10 11:29 UTC, vbuberen requested changes
Thanks for your contribution. Added a suggestion on improving the change.

Would ask you to update the PR title to comply with our contributors guide https://github.com/fluttercommunity/plus_plugins/blob/main/CONTRIBUTING.md#55-create-a-pull-request

2022-04-10 11:29 UTC, vbuberen commented on packages/device_info_plus/device_info_plus/android/src/main/java/dev/fluttercommunity/plus/device_info/MethodCallHandlerImpl.java
> +   * This key will change if a factory reset is performed on the device or if an APK signing key changes.
I think it is still not fully correct and we should also mention the difference for devices with Android versions before 8 and those with 8 and higher.

Suggest something like:
```
On devices with Android >= 8.0 (API level 26) returns an ID that is unique to each combination of app-signing key, user, and device. The value may change if a factory reset is performed on the device or if an APK signing key changes.
On devices with Android < 8.0 (API level 26) returns an ID that is randomly generated when the user first sets up the device and should remain constant for the lifetime of the user's device.
```

2022-04-10 19:57 UTC, vbuberen commented on packages/device_info_plus/device_info_plus/android/src/main/java/dev/fluttercommunity/plus/device_info/MethodCallHandlerImpl.java
> +   * This key will change if a factory reset is performed on the device or if an APK signing key changes.
@martinoyovo You might have missed this comment ☝🏻

2022-06-04 15:48 UTC, vbuberen commented
Thanks for your contirbution.

2022-06-04 15:49 UTC, vbuberen approved these changes

2022-06-04 15:49 UTC, merged

2022-06-18 00:02 UTC, a7medpa commented
FYI: I installed version 3.2.4 and in the generated_plugin.registrant.dart file, I got this error: Target of URI doesn't exist: 'package:device_info_plus_web/device_info_plus_web.dart'

The error goes when I downgrade back to 3.2.3