Fixes 828 Adds support for android display metrics.
fluttercommunity/plus_plugins pull request #829
Opened 2022-04-09 13:04 UTC by slightfoot

## Description

Fixes #828 

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated the version in `pubspec.yaml` and `CHANGELOG.md`.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/fluttercommunity/plus_plugins/blob/main/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

2022-04-11 07:40 UTC, miquelbeltran commented on packages/device_info_plus/device_info_plus/pubspec.yaml
> +  device_info_plus_platform_interface: 2.3.1
```suggestion
  device_info_plus_platform_interface: ^2.3.1
```
melos CI check is failing because it expects to use caret syntax

2022-04-12 20:51 UTC, vbuberen requested changes
I believe that physical size calculation needs changes.

Would also ask you to update the PR title to follow [the contribution guide](https://github.com/fluttercommunity/plus_plugins/blob/main/CONTRIBUTING.md#55-create-a-pull-request)

2022-04-12 20:51 UTC, vbuberen commented on packages/device_info_plus/device_info_plus_platform_interface/lib/model/android_device_info.dart
> +  /// The exact physical size in inches measured diagonally across the display.
It seems that we can't guarantee that the exact real size will be returned here and a different way should be used to calculate it: 
https://programmer.group/android-get-screen-physical-size-density-and-resolution.html

2022-06-11 09:34 UTC, The-Redhat commented
@slightfoot do you have time to look into completing this PR?

2022-06-11 09:57 UTC, slightfoot commented
Whoops. Yeah. I can look at this today.

2022-10-07 06:23 UTC, miquelbeltran commented
Hey! Due to changes in our contributor guidelines, all PRs should now:

- Have a title that follows the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/) format. e.g. `feat(package_name)!: feature description`
- **DO NOT** modify the CHANGELOG.md or the version in the `pubspec.yaml`. This is going to be an automated process now.

We would ask you kindly to update the PR following these changes.

Thanks!

2022-10-07 09:02 UTC, vbuberen commented
I will take care of this PR nearest days. Will both address the feedback and update according our new contributions guide.

2022-10-09 11:01 UTC, vbuberen commented on packages/device_info_plus/device_info_plus_platform_interface/lib/model/android_device_info.dart
> +  /// The exact physical size in inches measured diagonally across the display.
Checked and it seems that current implementation is correct.

2022-10-09 12:46 UTC, miquelbeltran approved these changes
I am not a 100% sure on this, but I think that if the platform interface is changed, this is a breaking issue, so the PR commit should contain a `!` and/or a `BREAKING CHANGE` footer.

2022-10-09 13:49 UTC, vbuberen commented
Yes, I think so. Updated the title.

2022-10-09 22:06 UTC, nohli commented
@The-Redhat could you please check if the latest commit in this branch works for you (since the PR was made for your app afaik)?

2022-10-10 06:22 UTC, The-Redhat commented
> @The-Redhat could you please check if the latest commit in this branch works for you (since the PR was made for your app afaik)?

Looks good to me. Thanks everybody for the effort.

2022-10-10 06:41 UTC, nohli approved these changes

2022-10-10 11:05 UTC, merged