chore(All plugins): Move all e2e tests to be integration_test
fluttercommunity/plus_plugins pull request #966
Opened 2022-07-17 13:29 UTC by Chever-John

create a new directory integration_test

## Description

Restructuring of files and directories in order for writing integration tests.

## Related Issues

It should be related to https://github.com/fluttercommunity/plus_plugins/issues/958

#958

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated the version in `pubspec.yaml` and `CHANGELOG.md`.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/fluttercommunity/plus_plugins/blob/main/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

2022-07-17 20:29 UTC, miquelbeltran commented
I converted the PR as draft, you can set it to Ready for review when you are done ;)

2022-07-18 02:00 UTC, Chever-John commented
@miquelbeltran 
yes, that's how it should be~

2022-07-18 09:00 UTC, miquelbeltran commented
I saw that for share_plus, sensor_plus and  package_info_plus the tests didn't do anything, for example: https://github.com/fluttercommunity/plus_plugins/runs/7385366900?check_suite_focus=true

That is because the CI command does not use the same project name as the one in the examples folder.

You need to do some some changes, and verify that they are correct.

2022-07-18 09:02 UTC, miquelbeltran requested changes

2022-07-18 09:02 UTC, miquelbeltran commented on .github/workflows/device_info_plus.yaml
> +          script: ./.github/workflows/scripts/integration-test.sh android device_info_plus_example
should be `device_info_example`

2022-07-18 09:02 UTC, miquelbeltran commented on .github/workflows/package_info_plus.yaml
> +          script: ./.github/workflows/scripts/integration-test.sh android package_info_plus_example
should be `package_info_example`

2022-07-18 09:02 UTC, miquelbeltran commented on .github/workflows/sensors_plus.yaml
> +          script: ./.github/workflows/scripts/integration-test.sh android sensors_plus_example
should be `sensors_example`

2022-07-18 09:02 UTC, miquelbeltran commented on .github/workflows/share_plus.yaml
> +          script: ./.github/workflows/scripts/integration-test.sh android share_plus_example
should be `share_example`

2022-07-18 09:05 UTC, Chever-John commented on .github/workflows/device_info_plus.yaml
> +          script: ./.github/workflows/scripts/integration-test.sh android device_info_plus_example
Copy that!

2022-07-18 11:14 UTC, merged